config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :listings do
    put 'favorite', on: :member
    delete 'unfavorite', on: :member

  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing
end

app/models/listing.rb
class Listing < ActiveRecord::Base

  has_many :favorites
  has_many :favorited_by, through: :favorites, source: :user

  def css_image_url
    bg_url = main_image_url.sub(/^https?\:/, '')
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites, :dependent => :destroy
  has_many :favorite_listings, through: :favorites, source: :listing

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @listings = Listing.all
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy, :favorite, :unfavorite]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def unfavorite
    @favorite = Favorite.where(:listing_id => @listing.id).first
    @favorite.destroy
    respond_to :js
  end

  def favorite
      current_user.favorites.create(:listing => @listing)
      # redirect_to root_url
      respond_to :js
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :description, :etsy_user_id, :price, :etsy_listing_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def etsy_listing_url(id)
    url = "http://www.etsy.com/listing/#{id}"
    return url
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/home/index.html.erb
<div class="cards-container">

  <% @listings.each do |listing| %>
    <div id="<%=listing.id%>" class="ProductCard product">
      <%= link_to(etsy_listing_url(listing.etsy_listing_id)) do %>
        <div class="product-img-container">
          <div class="hover-container">
            <div class="product-image" style="background-image:url('<%= listing.css_image_url %>');">
            </div>
          <% if user_signed_in? %>
            <% if current_user.favorites.where(:listing_id => listing.id).first.nil? %>
              <%= link_to "", "", :id => "fav-#{listing.id}", :class => "fav-link", :'data-id' => "#{listing.id}" %>
            <% else %>
              <%= link_to "", "", :id => "fav-#{listing.id}", :class => "fav-link active", :'data-id' => "#{listing.id}" %>
            <% end %>
          <% end %>
            </a>
          </div>
        </div>
      <% end %>
      <div class="top-right">
        <a href="" target="_blank" rel="nofollow" class="card-price button" ><%= number_to_currency(listing.price, :precision => 0) %></a>
      </div>

    </div>

  <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Btsy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class="primary-nav">
  <div class="wrapper navish">

    <div class="left-side">
      <div class="logo">
       BTSY<small>.io</small>
      </div>
      <h1 class="slogan">Homemade gifts for <s>you</s>, <s>mom</s>, <s>dad</s>, <s>freinds</s>, EVERYONE!</h1>
    </div>

    <div class="right-side">
      <div class="account">
          <% if user_signed_in? %>
            <%= current_user.email %>
            <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %>
          <% end %>
      </div>
    </div>

  </div>
</div>

<div class="GlobalNav-spacer"></div>
<p style="position:absolute;z-index:100;top:0;left:0" class="notice"><%= notice %></p>
<p style="position:absolute;z-index:100;top:0;left:0" class="alert"><%= alert %></p>
<div class="wrapper">
  <%= yield %>
</div>

</body>
</html>


<!-- <div class="GlobalNav-browse">
    <div class="GlobalNav-layout wrapper">
      <div class="GlobalNav-leftSide">
        <%= link_to "", root_url, :id => "lockup" %>
        <div class="nav-tabs">
          <%= link_to "Btsy", root_url %>
        </div>
      </div>

    </div>
  </div> -->

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :etsy_user_id %><br>
    <%= f.number_field :etsy_user_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :etsy_listing_id %><br>
    <%= f.number_field :etsy_listing_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/favorite.js.erb
{}

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Etsy user</th>
      <th>Price</th>
      <th>Etsy listing</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.description %></td>
        <td><%= listing.etsy_user_id %></td>
        <td><%= listing.price %></td>
        <td><%= listing.etsy_listing_id %></td>
        <td><%= image_tag(listing.main_image_url, :width => 200) %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Etsy user:</strong>
  <%= @listing.etsy_user_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Etsy listing:</strong>
  <%= @listing.etsy_listing_id %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>